#Basic of Tensor

In [2]:
import tensorflow as tf

In [3]:
tensor_zero_d=tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_d=tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [5]:
tensor_two_d=tf.constant([

                         [1,2,0],
                         [3,5,-1],
                         [1,5,6],
                         [2,3,8]

])

print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [6]:
tensor_three_d=tf.constant([

                            [[1,2,3],
                             [2,3,4]],

                            [[5,4,6],
                             [5,6,3]],

                            [[4,6,2],
                             [4,3,5]],

                            [[6,4,5],
                             [3,5,6]]
])

print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [2 3 4]]

 [[5 4 6]
  [5 6 3]]

 [[4 6 2]
  [4 3 5]]

 [[6 4 5]
  [3 5 6]]], shape=(4, 2, 3), dtype=int32)


In [7]:
print(tensor_two_d.shape)

(4, 3)


In [8]:
print(tensor_zero_d.dtype)

<dtype: 'int32'>


In [9]:
print(tensor_zero_d.ndim)

print(tensor_one_d.ndim)

print(tensor_two_d.ndim)

print(tensor_three_d.ndim)

print(tensor_zero_d.ndim,tensor_one_d.ndim,tensor_two_d.ndim,tensor_three_d.ndim)


0
1
2
3
0 1 2 3


In [10]:
tensor_four_d=tf.constant([

                            [[[1,2,3],
                             [2,3,4]],

                            [[5,4,6],
                             [5,6,3]],

                            [[4,6,2],
                             [4,3,5]],

                            [[6,4,5],
                             [3,5,6]]],

                            [[[1,2,3],
                             [2,3,4]],

                            [[5,4,6],
                             [5,6,3]],

                            [[4,6,2],
                             [4,3,5]],

                            [[6,4,5],
                             [3,5,6]]],

                            [[[1,2,3],
                             [2,3,4]],

                            [[5,4,6],
                             [5,6,3]],

                            [[4,6,2],
                             [4,3,5]],

                            [[6,4,5],
                             [3,5,6]]]

])

print(tensor_four_d)


tf.Tensor(
[[[[1 2 3]
   [2 3 4]]

  [[5 4 6]
   [5 6 3]]

  [[4 6 2]
   [4 3 5]]

  [[6 4 5]
   [3 5 6]]]


 [[[1 2 3]
   [2 3 4]]

  [[5 4 6]
   [5 6 3]]

  [[4 6 2]
   [4 3 5]]

  [[6 4 5]
   [3 5 6]]]


 [[[1 2 3]
   [2 3 4]]

  [[5 4 6]
   [5 6 3]]

  [[4 6 2]
   [4 3 5]]

  [[6 4 5]
   [3 5 6]]]], shape=(3, 4, 2, 3), dtype=int32)


In [11]:
print(tensor_four_d.ndim)

4


In [12]:
tensor_one_1_d=tf.constant([1,2,3],dtype=tf.float32)
print(tensor_one_1_d)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


#Casting

In [27]:
tensor_one_d_float=tf.constant([1,0.,-1,4],dtype=tf.float32)
caster_tensor=tf.cast(tensor_one_d_float,dtype=tf.int32)
print(tensor_one_d_float)
print(caster_tensor)

tf.Tensor([ 1.  0. -1.  4.], shape=(4,), dtype=float32)
tf.Tensor([ 1  0 -1  4], shape=(4,), dtype=int32)


In [28]:
caster_tensor_bool=tf.cast(tensor_one_d_float,dtype=tf.bool)
print(caster_tensor_bool)

tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


In [30]:
tensor_bool=tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [33]:
tensor_string=tf.constant("Hello World")
print(tensor_string)

tf.Tensor(b'Hello World', shape=(), dtype=string)


#numpy to tensorflow

In [22]:
import numpy as np

In [34]:
numpy_array=np.array([1,3,-3])
print(numpy_array)

[ 1  3 -3]


In [35]:
converted_tensor=tf.convert_to_tensor(numpy_array)
print(converted_tensor)

tf.Tensor([ 1  3 -3], shape=(3,), dtype=int64)


#Different Types of Methods

#Identy metrix


In [56]:
eye_tensor=tf.eye(
    num_rows=4,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [57]:
print(3*eye_tensor)

tf.Tensor(
[[3. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 3.]], shape=(4, 4), dtype=float32)


In [58]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=3,
    batch_shape=[3,2],
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(3, 2, 5, 3), dtype=float32)


In [59]:
eye_tensor=tf.eye(
    num_rows=4,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.bool,
    name=None
)

print(eye_tensor)

tf.Tensor(
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]], shape=(4, 4), dtype=bool)


#Fill method


In [60]:
fill_tensor=tf.fill(
    [2,4,3], 10, name=None, layout=None
)

print(fill_tensor)

tf.Tensor(
[[[10 10 10]
  [10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]
  [10 10 10]]], shape=(2, 4, 3), dtype=int32)


#One Method Where the value is 1

In [61]:
ones_tensor=tf.ones(
    [2,4,5],
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)

print(ones_tensor)

tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(2, 4, 5), dtype=float32)


#Ones Like method where the method change all the value to 1




In [62]:
ones_like_tensor=tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]], shape=(2, 4, 3), dtype=int32)


#Zero and Zeros Like (Same as Ones)

In [63]:
tensor_example=tf.fill(
    [3,4,5], 5, name=None, layout=None
)

print(tensor_example)

tf.Tensor(
[[[5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]]

 [[5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]]

 [[5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]]], shape=(3, 4, 5), dtype=int32)


In [65]:
zeros_tensor=tf.zeros(
    [2,4,3],
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)

print(zeros_tensor)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 4, 3), dtype=float32)


In [66]:
zeros_like_tensor=tf.zeros_like(tensor_example)
print(zeros_like_tensor)

tf.Tensor(
[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]], shape=(3, 4, 5), dtype=int32)


#Random Normal

```
tf.random.normal(
    shape,\\shape means dimentions
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
```



In [71]:
random_tensor=tf.random.normal(
    [4,3],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_tensor)

tf.Tensor(
[[ 0.30472398  2.5522964   0.65898794]
 [ 0.7404526   1.9065634   0.68850386]
 [ 0.6206508  -0.6755241  -1.2356551 ]
 [-1.0209091   1.0815138   0.29675013]], shape=(4, 3), dtype=float32)
