#Basic of Tensor

In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d=tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
#many 0d tensor combine 1d tensor.
tensor_one_d=tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [ ]:
#many 1d tensor combine 2d tensor
tensor_two_d=tf.constant([

                         [1,2,0],
                         [3,5,-1],
                         [1,5,6],
                         [2,3,8]

])

print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
# many 2d combines a 3d tensor
tensor_three_d=tf.constant([

                            [[1,2,3],
                             [2,3,4]],

                            [[5,4,6],
                             [5,6,3]],

                            [[4,6,2],
                             [4,3,5]],

                            [[6,4,5],
                             [3,5,6]]
])

print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [2 3 4]]

 [[5 4 6]
  [5 6 3]]

 [[4 6 2]
  [4 3 5]]

 [[6 4 5]
  [3 5 6]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(tensor_two_d.shape) #to check the shape of the tensor we use shape

(4, 3)


In [ ]:
print(tensor_zero_d.dtype) #to check the data type of the tensor we use dtype

<dtype: 'int32'>


In [ ]:
print(tensor_zero_d.ndim) #to check the dimention of the tensor we use ndim

print(tensor_one_d.ndim)

print(tensor_two_d.ndim)

print(tensor_three_d.ndim)

print(tensor_zero_d.ndim,tensor_one_d.ndim,tensor_two_d.ndim,tensor_three_d.ndim)


0
1
2
3
0 1 2 3


In [ ]:
# many 3d combine 4d tensor
tensor_four_d=tf.constant([

                            [[[1,2,3],
                             [2,3,4]],

                            [[5,4,6],
                             [5,6,3]],

                            [[4,6,2],
                             [4,3,5]],

                            [[6,4,5],
                             [3,5,6]]],

                            [[[1,2,3],
                             [2,3,4]],

                            [[5,4,6],
                             [5,6,3]],

                            [[4,6,2],
                             [4,3,5]],

                            [[6,4,5],
                             [3,5,6]]],

                            [[[1,2,3],
                             [2,3,4]],

                            [[5,4,6],
                             [5,6,3]],

                            [[4,6,2],
                             [4,3,5]],

                            [[6,4,5],
                             [3,5,6]]]

])

print(tensor_four_d)


tf.Tensor(
[[[[1 2 3]
   [2 3 4]]

  [[5 4 6]
   [5 6 3]]

  [[4 6 2]
   [4 3 5]]

  [[6 4 5]
   [3 5 6]]]


 [[[1 2 3]
   [2 3 4]]

  [[5 4 6]
   [5 6 3]]

  [[4 6 2]
   [4 3 5]]

  [[6 4 5]
   [3 5 6]]]


 [[[1 2 3]
   [2 3 4]]

  [[5 4 6]
   [5 6 3]]

  [[4 6 2]
   [4 3 5]]

  [[6 4 5]
   [3 5 6]]]], shape=(3, 4, 2, 3), dtype=int32)


In [ ]:
print(tensor_four_d.ndim)

4


In [ ]:
tensor_one_1_d=tf.constant([1,2,3],dtype=tf.float32)
print(tensor_one_1_d)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


#Casting
##Casting means changing the data type of the tensor. Like we have float and we want to change it to int so we will use casting

In [ ]:
tensor_one_d_float=tf.constant([1,0.,-1,4],dtype=tf.float32)
caster_tensor=tf.cast(tensor_one_d_float,dtype=tf.int32) # we are using cast method to convert float32 to int32
print(tensor_one_d_float)
print(caster_tensor)

tf.Tensor([ 1.  0. -1.  4.], shape=(4,), dtype=float32)
tf.Tensor([ 1  0 -1  4], shape=(4,), dtype=int32)


In [ ]:
caster_tensor_bool=tf.cast(tensor_one_d_float,dtype=tf.bool) # converting into boolien function using cast method
print(caster_tensor_bool)

tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


In [ ]:
tensor_bool=tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_string=tf.constant("Hello World")
print(tensor_string)

tf.Tensor(b'Hello World', shape=(), dtype=string)


#numpy to tensorflow

In [ ]:
import numpy as np

In [ ]:
numpy_array=np.array([1,3,-3])
print(numpy_array)

[ 1  3 -3]


In [ ]:
converted_tensor=tf.convert_to_tensor(numpy_array)
print(converted_tensor)

tf.Tensor([ 1  3 -3], shape=(3,), dtype=int64)


#Different Types of Methods

#Identy metrix


In [2]:
import tensorflow as tf
eye_tensor=tf.eye(
    num_rows=4,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [3]:
casted_eye_tensor = tf.cast(eye_tensor, dtype=tf.int32)
print(casted_eye_tensor)
print(3*eye_tensor)

tf.Tensor(
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[3. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 3.]], shape=(4, 4), dtype=float32)


In [ ]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=3,
    batch_shape=[3,2],
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(3, 2, 5, 3), dtype=float32)


In [ ]:
eye_tensor=tf.eye(
    num_rows=4,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.bool,
    name=None
)

print(eye_tensor)

tf.Tensor(
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]], shape=(4, 4), dtype=bool)


#Fill method


In [ ]:
fill_tensor=tf.fill(
    [2,4,3], 10, name=None, layout=None  # tf.fill(dims, value, name=None, layout=None)

)

print(fill_tensor)

tf.Tensor(
[[[10 10 10]
  [10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]
  [10 10 10]]], shape=(2, 4, 3), dtype=int32)


#One Method Where the value is 1

In [ ]:
#tf.ones(
#    shape,
#    dtype=tf.dtypes.float32,
#    name=None,
#    layout=None
#)

ones_tensor=tf.ones(
    [2,4,5],
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)

print(ones_tensor)

tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(2, 4, 5), dtype=float32)


#Ones Like method where the method change all the value to 1




In [ ]:
#tf.ones_like(
#    input, dtype=None, name=None, layout=None
#)


ones_like_tensor=tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]], shape=(2, 4, 3), dtype=int32)


#Zero and Zeros Like (Same as Ones)

In [ ]:
#tf.fill(
#    dims, value, name=None, layout=None
#)

tensor_example=tf.fill(
    [3,4,5], 5, name=None, layout=None
)

print(tensor_example)

tf.Tensor(
[[[5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]]

 [[5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]]

 [[5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]
  [5 5 5 5 5]]], shape=(3, 4, 5), dtype=int32)


In [ ]:
#tf.zeros(
#    shape,
#    dtype=tf.dtypes.float32,
#    name=None,
#    layout=None
#)

zeros_tensor=tf.zeros(
    [2,4,3],
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)

print(zeros_tensor)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 4, 3), dtype=float32)


In [ ]:
zeros_like_tensor=tf.zeros_like(tensor_example)
print(zeros_like_tensor)

tf.Tensor(
[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]], shape=(3, 4, 5), dtype=int32)


#Random Normal
## https://www.acsu.buffalo.edu/~adamcunn/probability/normal.html

```
tf.random.normal(
    shape,\\shape means dimentions
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
```



In [ ]:
random_tensor=tf.random.normal(
    [4,3],
    mean=0.0, # mean means that all the random value will be near that mean value
    stddev=1.0,  # stddev means standard deviation. A smaller stddev means the values are closer to the mean (less spread out).A larger stddev means the values are more spread out.
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_tensor)

tf.Tensor(
[[-2.4662292  -0.5715262  -0.80449146]
 [-0.62035376 -1.6006722   0.07374258]
 [ 0.03874078 -1.4387479   0.7660149 ]
 [-0.01358966 -1.0341055   1.0039945 ]], shape=(4, 3), dtype=float32)


In [ ]:
random_tensor=tf.random.normal(
    [4,3],
    mean=20.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_tensor)

tf.Tensor(
[[21.32492  19.698435 21.128544]
 [22.294464 19.846203 20.302753]
 [18.524006 19.362352 19.242605]
 [19.462807 20.648132 21.247866]], shape=(4, 3), dtype=float32)


#Random Uniform
### For uniform insted of mean and standard deviation we use min value and max

In [5]:
#tf.random.uniform(
#    shape,
#    minval=0,
#    maxval=None,
#    dtype=tf.dtypes.float32,
#    seed=None,
#    name=None
#)


random_uniform_tensor=tf.random.uniform(
    [2,3],
    minval=3,
    maxval=10,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print (random_uniform_tensor)

tf.Tensor(
[[4.118925  3.2364697 8.37015  ]
 [3.2636926 6.805786  6.256915 ]], shape=(2, 3), dtype=float32)


#Seed
## seed many ganarate the same value again and again

In [10]:
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)


In [9]:
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)
